### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by aptakhin** [aptakhin/dstate#3]
### Draft way to 1.0

- [ ] add Redis for locks
- [ ] add SQLModel support for persistence
- [ ] add SQLAlchemy==2 support for persistence
- [ ] provide support for hierarchical SM with seamless storages persistence
- [ ] timers support
- [ ] extended concurrent test support
- [ ] stabilize api
- [ ] docs: description, examples
